// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:json_annotation/json_annotation.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYRXNOr7JhMEp7M6H16GUXrV5c20CRhzw',
    appId: '1:97582202787:web:86919087b70202ed3f6416',
    messagingSenderId: '97582202787',
    projectId: 'poly-brewers',
    authDomain: 'poly-brewers.firebaseapp.com',
    storageBucket: 'poly-brewers.appspot.com',
    measurementId: 'G-84EQDH85F6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbAAVWRYO1oxCzjcyHW0G1wQJS1qPCaYc',
    appId: '1:97582202787:android:7d42ff115eb81c8c3f6416',
    messagingSenderId: '97582202787',
    projectId: 'poly-brewers',
    storageBucket: 'poly-brewers.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEwbbaEW-Tbou9hoCNxZIGbKpTUhIq-jU',
    appId: '1:97582202787:ios:4cf71c08d7bd93763f6416',
    messagingSenderId: '97582202787',
    projectId: 'poly-brewers',
    storageBucket: 'poly-brewers.appspot.com',
    iosClientId:
        '97582202787-temaek9fjegjct7kv7588m1r5vg3a2uc.apps.googleusercontent.com',
    iosBundleId: 'com.example.polyBrewers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEwbbaEW-Tbou9hoCNxZIGbKpTUhIq-jU',
    appId: '1:97582202787:ios:4cf71c08d7bd93763f6416',
    messagingSenderId: '97582202787',
    projectId: 'poly-brewers',
    storageBucket: 'poly-brewers.appspot.com',
    iosClientId:
        '97582202787-temaek9fjegjct7kv7588m1r5vg3a2uc.apps.googleusercontent.com',
    iosBundleId: 'com.example.polyBrewers',
  );
}
